provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  garbage-collect:
    lang: go
    handler: ./garbage-collect
    image: functions/garbage-collect:0.4.6
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
      read_timeout: 30s
      write_timeout: 30s
    environment_file:
      - gateway_config.yml
    secrets:
      - basic-auth-user
      - basic-auth-password
      - payload-secret

